### ISSUE TITLE
Question About Matching

### ISSUE THREAD

**Issue by cnmckee** [amirbar/DETReg#17]
Hello- first off, great work! I have really enjoyed working through this repo.
It appears that the Hungarian Matcher does not use the output and target object embeddings when determining the matching. Why is this? It appears the embeddings still contribute to the loss. 
Also, I understand that there are usually more outputs than targets- In the paper it says you pad the targets with non-objects (I assumed these would be something like random crops from portions of the image for which selective search returned no boxes), but in the code it looks like you discard unmatched outputs as non-objects. Can you explain this a bit more? It seems to me that with no non-object targets, the DETR model would simply learn to assign an object class to every detection no matter what and that portion of the loss would quickly collapse to zero. 
Thanks again!

**Comment by amirbar** [comment]
Thank you for your interest in our work! 

We've tried the most simple approach which is to base the matching over the localization score. My intuition was that the matching process is already noisy in our setting and adding the object embeddings might only make it noisier. However, it seems interesting to explore different ways to use the object embedding similarity in the matching, especially because it might lead to some synergy (can the object embedding loss contribute and improves localization..?)

As for the outputs and targets - we have a single logit for object/no-object. Every prediction is assigned with 0 or 1 target according to the matching. We then apply the Focal Loss (see https://github.com/amirbar/DETReg/blob/main/models/segmentation.py#L212).
